name: rejistra
description: "A new Flutter project."

publish_to: 'none'
# La ligne 'suffix.' a été supprimée d'ici.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # J'ai ajusté ceci pour correspondre au SDK de votre prototype

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared # <- C'est correct
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  data_table_2: ^2.6.0
  intl: ^0.20.2
  responsive_builder: ^0.7.1
  supabase_flutter: ^2.10.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true