name: rejistra
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  data_table_2: ^2.6.0
  intl: ^0.20.2
  responsive_builder: ^0.7.1
  supabase_flutter: ^2.10.3

  # --- AJOUTS POUR LA PHASE 1 ---

  # Pour l'exportation Excel
  excel: ^4.0.0

  # Pour la génération de PDF
  pdf: ^3.10.8

  # Pour l'impression/sauvegarde du PDF sur le web
  printing: ^5.12.0

  # Pour sauvegarder les fichiers (Excel) sur le web
  universal_html: ^2.2.4

  # --- AJOUT POUR CORRIGER LES ERREURS photo_uploader.dart ---
  image_picker: ^1.1.2 # Ajout de la dépendance manquante

  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- AJOUT POUR LES PDF ---
  assets:
    - assets/fonts/